### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/internal/zzah

### ISSUE THREAD

**Issue by duzenko** [dandar3/android-google-play-services-ads#1]
Hi, I downloaded and added to the workspace this and all the required libs and now I get this error:
On top of that I get a java.lang.NoSuchFieldError: AdsAttrs in Visual Editor
Any ideas?
![untitled](https://cloud.githubusercontent.com/assets/1481807/16651720/8ebe91b0-444e-11e6-8b40-9a084ce8f9b6.png)

**Comment by dandar3** [comment]
@duzenko
Have you taken specifically 9.0.2 releases of each proiect (either using the SVN urls for the tags or the zip versions from the Release tab) or just went straight for each project main page **Clone or Download**? 

Cause in the middle of updating them to version 9.2.0 - possibly the issue might be caused by the mix of 9.0.2 and 9.2.0 code going on at the master / trunk level at the moment. 

Can you hold on for a couple hours until I'm finished updating and will come back to you to replicate the issue and respond in this thread.

Thanks,
Dan

**Comment by duzenko** [comment]
No, I ended up with a library downloaded from old google link

**Comment by dandar3** [comment]
Google Play Services 9.2.0 libraries are all up now.

Not sure what "old Google link" you used, but out of curiousity can you share it? Let me know if you're sorted out or you want me to go on.

I was able to replicate your layout preview exception issue, not sure whether I can do anything about it but I'll see if there's a way. I must confess I don't use the preview much, especially since ADT plugin stopped being maintaned, I always tried to learn the XML syntax for better control on things, but might be just me.

I wasn't able to replicate the **Unable to execute dex: Multiple dex files define ...** issue, may be that now all libraries have been uploaded and they all match 9.2.0 release, can try again. Maybe do a **Project (top menubar) > Clean... > Clean all** projects after updating to make sure your build starts fresh.

Tested with:
- Eclipse 4.6.0
- ADT plugin 23.0.7.2120684
- Android SDK Tools 25.1.7
- Android SDK Platform-Tools 24
- Android SDK Build-Tools 24

**Comment by duzenko** [comment]
https://github.com/denny0223/google_play_services.zips/blob/master/google_play_services_4132530_r14.zip

**Comment by dandar3** [comment]
Oh man, that looks like Google Play Services library **4.1.32 (978161-30)** from 14 Jan 2014, I'm not even sure whether that would work or for how long, but good luck I guess! :-)

**Comment by dandar3** [comment]
As to the main issue (**Multiple dex files define Lcom/google/android/gms/internal/zzah**), use a search tool like the one below, search for `com.google.android.gms.internal.zzah` class at your workspace location.

It should find it in `google-play-services-basement/libs/google-play-services-basement.jar` only (as of v9.2.0). If it finds in multiple places you've maybe imported the project multiple times, or a mix of library versions (in case the class moved in between packages), the SDK build tools version you're using might have a bug (basement library is referenced by multiple projects but the tools should correctly process only once) etc.
- `java -jar ClassFinder-2.0.0-runnable.jar`
- https://github.com/gvenzl/ClassFinder/releases
- https://venzi.wordpress.com/2013/10/25/java-class-finding-tool-classfinder/

**Comment by dandar3** [comment]
Finally on the `AdsAttr` layout preview issue, decompiling `com.google.android.gms.ads.internal.client.zzk` (top of the stack-trace, from `google-play-services-ads-lite.jar`) with [JD-GUI](http://jd.benow.ca/), it appears to reference `AdsAttr` from the `basement` project (`com.google.android.gms` is the package for that, see its `AndroidManifest.xml`).

```
  import com.google.android.gms.R.styleable;

  public zzk(Context paramContext, AttributeSet paramAttributeSet)
  {
    TypedArray localTypedArray = paramContext.getResources().obtainAttributes(paramAttributeSet, R.styleable.AdsAttrs);
...
```

What you can do as a workaround is to copy the `<declare-styleable name="AdsAttrs">...</declare-styleable>` line from `/google-play-services-ads-lite/res/values/values.xml` into `/google-play-services-basement/res/values/values.xml`, rebuild all projects and reopen the XML layout preview, that seemed to have worked for me.

I have no idea whether this constructor is only referenced from Eclipse layout preview and why it hasn't come up as an issue with say Android Studio, but I doubt if reporting this to Google to fix it and reference the right package it will get done as they discontinued support for Eclipse, but feel free to report it if you want.

**Comment by linhnv106** [comment]
@dandar3 I got the same prolem  `Conversion to Dalvik format failed: Unable to execute dex: Multiple dex files define Lcom/google/android/gms/internal/zzfd;`
I used ClassFinder and here is the  result :

```
/android-google-play-services-ads-master/libs/google-play-services-ads.jar
--
/android-google-play-services-basement-11.0.2/android-google-play-services-basement-11.0.2/libs/google-play-services-basement.jar
/google_play_services/google-play-services/libproject/google-play-services_lib/libs/google-play-services.jar

```
How can I resolve the prolem? please help

**Comment by dandar3** [comment]
@linhnv106 
What is `google-play-services_lib` project and why do you think you need it? Looks like the old Google Play Services project delivered by the SDK Manager.

If you want `google-play-services-ads` project, I would recommend removing all dependency projects you are using now and import `google-play-serves-ads` using its team-set file, for v11.0.2:
- See the video at the end of this page on how to import / download team sets:
https://github.com/dandar3/android-google-play-services-README/tree/11.0.2
- Project set file for GPS Ads project:
https://raw.githubusercontent.com/dandar3/android-google-play-services-ads/11.0.2/.projectset

**Comment by linhnv106** [comment]
@dandar3 thank you, I have to make all libs in same version 11.02. 
btw are you planing to export billing lib ?

**Comment by dandar3** [comment]
@linhnv106 
That is the beauty of the team sets - it contains links to all required dependenat libraries so when you pick a top level project, it will pull down all projects with the same version.

Google Billing Library 1.0 available from here:
https://github.com/dandar3/android-google-services-billing/tree/1.0
