### ISSUE TITLE
Please update google play ads library

### ISSUE THREAD

**Issue by vijaybhairavjibhaiaslaliya** [dandar3/android-google-play-services-ads#6]
hi dandar3
we always use your library to our project in eclipse, and you give google play ads library 15.0.0 (android 8.1.0) please update your google play ads library 18.3.0 (android 10.0.0) as soon as possible.

thanks for your support.

**Comment by vijaybhairavjibhaiaslaliya** [comment]
ok thanks for your support

**Comment by dandar3** [comment]
We're working on it, please wait for a few more days.

**Comment by dandar3** [comment]
Sorry it tooks us so long, we're making good progress and hope to have it the next day or so.

**Comment by strength0179** [comment]
萬歲～～

**Comment by dandar3** [comment]
Version 18.3.0 is now available, please see the import notes in the README.md. 
https://github.com/dandar3/android-google-play-services-ads/tree/18.3.0

Note that this version requires Jetpack AndroidX libraries which are included in the project set import, which replace the Android Support Libraries. I would recommend starting a new workspace where you import the new GPS Ads library along a simple app to test the ads functionality.

Still working on AndroidX Appcompat if you're using that as well, will be coming tomorrow.

**Comment by vijaybhairavjibhaiaslaliya** [comment]
thank you ....thank you so much for your hard work

**Comment by dandar3** [comment]
You'are more than welcome! (Y)

I was able to run a quick test implementing a banner test ad following the coding instructions from the standard Google page - `<manifest>` change with test AdMob App ID, `MobileAds.initialize()` in `MainActivity.java`, `<com.google.android.gms.ads.AdView>` with the test unit id in `activity_main.xml` and the `mAdView.loadAd()` in the `MainActivity.java`, as provided in the banner instructions page.

Before that obviously import the `.projectset` into your workspace and add `google-play-services-ads` as a library to your app. The ad will show in a few seconds, obviously depending on the speed of the device and the network connection.

If you're having problems with importing the .projectset because of missing the Subversive Eclipse plugin, let me know and I will write a blog post on how to install it. I've been testing all these last few days with the latest version of Eclipse 2019-09 which is quite noticibly faster. PS: Same as before I would recommend trying the new Eclipse in a new workspace so you don't break your existing one. You can have as many Eclipses as you want as long as you keep the workspaces separate as it might break internal structures, it asks you whether to upgrade it when using it with a new version.

**Comment by vijaybhairavjibhaiaslaliya** [comment]
Sorry to bother you again. But Every time i import this new GPS ads library, i didn't find below 3 library pack. It's give me importing Project error like some project may not be loaded. Can you upload or give me below 3 library if you have ? or can you show me how to import below 3 library ?

androidx-browser,   androidx-collection,   androidx-core

**Comment by dandar3** [comment]
Forgot to mention you might want to enable the `manifestmerger` in your application, I wrote a quick post about this here. https://dandar3.blogspot.com/2019/12/eclipse-android-manifest-merger.html

Also for Jetpack (AndroidX) related libraries, please follow this page and create related issues there (Y)
https://github.com/dandar3/android-androidx-README
